### PR TITLE
Remove core async

### PR DESCRIPTION
**Pull request by RokLenarcic**
From:
```
(time (require '[com.fulcrologic.guardrails.malli.core]))
"Elapsed time: 7330.943292 msecs"
```
 to
```
(time (require '[com.fulcrologic.guardrails.malli.core]))
"Elapsed time: 3880.868583 msecs"
```

### CODE REVIEW

**Comment by RokLenarcic** [comment]
I am not sure that tests cover async use case, so I'll try to fix more tests.

**Comment by RokLenarcic** [comment]
Tested it by hand.

**Comment by gnl** [comment]
You know what, as hinted at in the original issue, we ended up deciding to get rid of the async feature altogether – it's no longer needed with the newest performance improvements (that's why I wanted to hold off on this PR initially, hope you didn't put too much time into it). Would you mind updating the PR to just cleanly remove everything related to the async checks?

**Comment by RokLenarcic** [comment]
No problem, but I'll do it tomorrow. It's late here.

**Comment by RokLenarcic** [comment]
Didn't take long, so I did it now.

**Review by awkay — APPROVED** [review]

**Pull request merged**
